#!/bin/bash

wget -q -O - https://bitbucket.org/mutt/mutt/downloads/mutt-1.5.23.tar.gz | tar xvfz -

# Apply side bar patch
wget -q -O - http://lunar-linux.org/~tchan/mutt/patch-1.5.23.sidebar.20140412.txt | patch -p1

# Apply trash patch
wget -q -O - http://cedricduval.free.fr/mutt/patches/download/patch-1.5.5.1.cd.trash_folder.3.4 | patch -p1

# Configure Mutt
./configure --prefix=/usr     \
            --sysconfdir=/etc \
            --with-docdir=/usr/share/doc/mutt-1.5.23 \
            --enable-pop      \
            --enable-imap     \
            --enable-hcache   \
            --without-qdbm    \
            --with-gdbm       \
            --without-bdb     \
            --without-tokyocabinet \
            --enable-smtp         \
            --with-ssl         \
            --with-gnutls      \
            --with-regex


# Build Mutt
touch configure.ac aclocal.m4 configure Makefile.am Makefile.in

make

# Install Mutt
sudo make install