#!/bin/bash

#Copies ushahidi codes to test server over rsync
# Author: Henry Addo <henry@addhen.org>"

rsync -e 'ssh -p 1313' -avz --exclude=application/config/config.php  --exclude=.htaccess --exclude=application/logs/ --exclude=application/cache --exclude=application/config/database.php --exclude=application/config/alerts.php --delete /home/eyedol/Work/Workspace/ushahidi-web/ /var/www/ushahidi/
