#!/bin/bash

#Copies ushahidi codes to a test server over rsync
# Author: Henry Addo <henry@addhen.org>"

curl -v -u 'admin:admin' -F 'task=comments' \
-F 'action=delete' \
-F 'comment_id=1' \
'http://localhost/ush/api'
