#!/bin/bash

#Copies ushahidi codes to a test server over rsync
# Author: Henry Addo <henry@addhen.org>"

curl -v -u 'admin' -F 'task=category' \
-F 'action=add' \
-F 'category_title=Test+api+category+title' \
-F 'category_description=Testing+with+the+api' \
-F 'parent_id=0' \
-F 'category_color=ff00ff' \
'http://localhost/tunis/api'
