#!/bin/bash

#Copies ushahidi codes to a test server over rsync
# Author: Henry Addo <henry@addhen.org>"

curl -v -u 'admin:admin' -F 'task=comments' \
-F 'action=add' \
-F 'incident_id=1' \
-F 'comment_author=Henry Addo' \
-F 'comment_description=Passing comment via the api' \
-F 'comment_email=henry@ushahidi.com' \
'http://localhost/ush/api'
