#!/bin/bash

#Copies ushahidi codes to a test server over rsync
# Author: Henry Addo <henry@addhen.org>"

curl -v -u 'dalezak@gmail.com:;YAPqXRV8iI2vlB' -F 'task=reports' \
-F 'by=approved' \
 'https://tedxmap.crowdmap.com/api'
