#!/bin/bash

#Copies ushahidi codes to a test server over rsync
# Author: Henry Addo <henry@addhen.org>"

curl -v -u 'admin' -F 'task=category' \
-F 'action=edit' \
-F 'category_title=Test+api+category+title+editted' \
-F 'category_description=Testing+with+the+api+editted' \
-F 'category_id=5' \
-F 'parent_id=0' \
-F 'category_color=ff0000' \
'http://localhost/ush/api'
