#!/bin/bash

#Copies ushahidi codes to a test server over rsync
# Author: Henry Addo <henry@addhen.org>"

curl -v -u 'admin:admin' -F 'task=reports' \
-F 'action=edit' \
-F 'incident_id=1' \
-F 'incident_title=Hello Ushahidi Edited' \
-F 'incident_description=Description Edited' \
-F 'incident_date=03/18/2009' \
-F 'incident_hour=10' \
-F 'incident_minute=10' \
-F 'incident_ampm=pm' \
-F 'incident_category=1,2,' \
-F 'latitude=-1.28730007' \
-F 'longitude=36.82145118200820' \
-F 'location_id=2' \
-F 'location_name=accra' \
-F 'person_first=Henry Addo' \
-F 'person_last=Addo' \
-F 'incident_active=1' \
-F 'incident_verified=1' \
-F 'person_email=henry@ushahidi.com' \
'http://localhost/ush/api'
